//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18052
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceControl.MainServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkItem", Namespace="http://cocoin.info/MainService")]
    [System.SerializableAttribute()]
    public partial class WorkItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime receiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stockIdField;
        
        private int currentField;
        
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime receiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                if ((this.receiveDateField.Equals(value) != true)) {
                    this.receiveDateField = value;
                    this.RaisePropertyChanged("receiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string stockId {
            get {
                return this.stockIdField;
            }
            set {
                if ((object.ReferenceEquals(this.stockIdField, value) != true)) {
                    this.stockIdField = value;
                    this.RaisePropertyChanged("stockId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int current {
            get {
                return this.currentField;
            }
            set {
                if ((this.currentField.Equals(value) != true)) {
                    this.currentField = value;
                    this.RaisePropertyChanged("current");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cocoin.info/MainService", ConfigurationName="MainServiceReference.MainServiceSoap")]
    public interface MainServiceSoap {
        
        // CODEGEN: 命名空間 http://cocoin.info/MainService 的項目名稱  GetWorkResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://cocoin.info/MainService/GetWork", ReplyAction="*")]
        ServiceControl.MainServiceReference.GetWorkResponse GetWork(ServiceControl.MainServiceReference.GetWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cocoin.info/MainService/GetWork", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceControl.MainServiceReference.GetWorkResponse> GetWorkAsync(ServiceControl.MainServiceReference.GetWorkRequest request);
        
        // CODEGEN: 命名空間 http://cocoin.info/MainService 的項目名稱  RunInitResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://cocoin.info/MainService/RunInit", ReplyAction="*")]
        ServiceControl.MainServiceReference.RunInitResponse RunInit(ServiceControl.MainServiceReference.RunInitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cocoin.info/MainService/RunInit", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceControl.MainServiceReference.RunInitResponse> RunInitAsync(ServiceControl.MainServiceReference.RunInitRequest request);
        
        // CODEGEN: 命名空間 http://cocoin.info/MainService 的項目名稱  RunWorkInitResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://cocoin.info/MainService/RunWorkInit", ReplyAction="*")]
        ServiceControl.MainServiceReference.RunWorkInitResponse RunWorkInit(ServiceControl.MainServiceReference.RunWorkInitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cocoin.info/MainService/RunWorkInit", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceControl.MainServiceReference.RunWorkInitResponse> RunWorkInitAsync(ServiceControl.MainServiceReference.RunWorkInitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWorkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWork", Namespace="http://cocoin.info/MainService", Order=0)]
        public ServiceControl.MainServiceReference.GetWorkRequestBody Body;
        
        public GetWorkRequest() {
        }
        
        public GetWorkRequest(ServiceControl.MainServiceReference.GetWorkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWorkRequestBody {
        
        public GetWorkRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWorkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWorkResponse", Namespace="http://cocoin.info/MainService", Order=0)]
        public ServiceControl.MainServiceReference.GetWorkResponseBody Body;
        
        public GetWorkResponse() {
        }
        
        public GetWorkResponse(ServiceControl.MainServiceReference.GetWorkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocoin.info/MainService")]
    public partial class GetWorkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceControl.MainServiceReference.WorkItem GetWorkResult;
        
        public GetWorkResponseBody() {
        }
        
        public GetWorkResponseBody(ServiceControl.MainServiceReference.WorkItem GetWorkResult) {
            this.GetWorkResult = GetWorkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunInitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunInit", Namespace="http://cocoin.info/MainService", Order=0)]
        public ServiceControl.MainServiceReference.RunInitRequestBody Body;
        
        public RunInitRequest() {
        }
        
        public RunInitRequest(ServiceControl.MainServiceReference.RunInitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RunInitRequestBody {
        
        public RunInitRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunInitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunInitResponse", Namespace="http://cocoin.info/MainService", Order=0)]
        public ServiceControl.MainServiceReference.RunInitResponseBody Body;
        
        public RunInitResponse() {
        }
        
        public RunInitResponse(ServiceControl.MainServiceReference.RunInitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocoin.info/MainService")]
    public partial class RunInitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RunInitResult;
        
        public RunInitResponseBody() {
        }
        
        public RunInitResponseBody(string RunInitResult) {
            this.RunInitResult = RunInitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunWorkInitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunWorkInit", Namespace="http://cocoin.info/MainService", Order=0)]
        public ServiceControl.MainServiceReference.RunWorkInitRequestBody Body;
        
        public RunWorkInitRequest() {
        }
        
        public RunWorkInitRequest(ServiceControl.MainServiceReference.RunWorkInitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RunWorkInitRequestBody {
        
        public RunWorkInitRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunWorkInitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunWorkInitResponse", Namespace="http://cocoin.info/MainService", Order=0)]
        public ServiceControl.MainServiceReference.RunWorkInitResponseBody Body;
        
        public RunWorkInitResponse() {
        }
        
        public RunWorkInitResponse(ServiceControl.MainServiceReference.RunWorkInitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocoin.info/MainService")]
    public partial class RunWorkInitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RunWorkInitResult;
        
        public RunWorkInitResponseBody() {
        }
        
        public RunWorkInitResponseBody(string RunWorkInitResult) {
            this.RunWorkInitResult = RunWorkInitResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MainServiceSoapChannel : ServiceControl.MainServiceReference.MainServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainServiceSoapClient : System.ServiceModel.ClientBase<ServiceControl.MainServiceReference.MainServiceSoap>, ServiceControl.MainServiceReference.MainServiceSoap {
        
        public MainServiceSoapClient() {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceControl.MainServiceReference.GetWorkResponse ServiceControl.MainServiceReference.MainServiceSoap.GetWork(ServiceControl.MainServiceReference.GetWorkRequest request) {
            return base.Channel.GetWork(request);
        }
        
        public ServiceControl.MainServiceReference.WorkItem GetWork() {
            ServiceControl.MainServiceReference.GetWorkRequest inValue = new ServiceControl.MainServiceReference.GetWorkRequest();
            inValue.Body = new ServiceControl.MainServiceReference.GetWorkRequestBody();
            ServiceControl.MainServiceReference.GetWorkResponse retVal = ((ServiceControl.MainServiceReference.MainServiceSoap)(this)).GetWork(inValue);
            return retVal.Body.GetWorkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceControl.MainServiceReference.GetWorkResponse> ServiceControl.MainServiceReference.MainServiceSoap.GetWorkAsync(ServiceControl.MainServiceReference.GetWorkRequest request) {
            return base.Channel.GetWorkAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceControl.MainServiceReference.GetWorkResponse> GetWorkAsync() {
            ServiceControl.MainServiceReference.GetWorkRequest inValue = new ServiceControl.MainServiceReference.GetWorkRequest();
            inValue.Body = new ServiceControl.MainServiceReference.GetWorkRequestBody();
            return ((ServiceControl.MainServiceReference.MainServiceSoap)(this)).GetWorkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceControl.MainServiceReference.RunInitResponse ServiceControl.MainServiceReference.MainServiceSoap.RunInit(ServiceControl.MainServiceReference.RunInitRequest request) {
            return base.Channel.RunInit(request);
        }
        
        public string RunInit() {
            ServiceControl.MainServiceReference.RunInitRequest inValue = new ServiceControl.MainServiceReference.RunInitRequest();
            inValue.Body = new ServiceControl.MainServiceReference.RunInitRequestBody();
            ServiceControl.MainServiceReference.RunInitResponse retVal = ((ServiceControl.MainServiceReference.MainServiceSoap)(this)).RunInit(inValue);
            return retVal.Body.RunInitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceControl.MainServiceReference.RunInitResponse> ServiceControl.MainServiceReference.MainServiceSoap.RunInitAsync(ServiceControl.MainServiceReference.RunInitRequest request) {
            return base.Channel.RunInitAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceControl.MainServiceReference.RunInitResponse> RunInitAsync() {
            ServiceControl.MainServiceReference.RunInitRequest inValue = new ServiceControl.MainServiceReference.RunInitRequest();
            inValue.Body = new ServiceControl.MainServiceReference.RunInitRequestBody();
            return ((ServiceControl.MainServiceReference.MainServiceSoap)(this)).RunInitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceControl.MainServiceReference.RunWorkInitResponse ServiceControl.MainServiceReference.MainServiceSoap.RunWorkInit(ServiceControl.MainServiceReference.RunWorkInitRequest request) {
            return base.Channel.RunWorkInit(request);
        }
        
        public string RunWorkInit() {
            ServiceControl.MainServiceReference.RunWorkInitRequest inValue = new ServiceControl.MainServiceReference.RunWorkInitRequest();
            inValue.Body = new ServiceControl.MainServiceReference.RunWorkInitRequestBody();
            ServiceControl.MainServiceReference.RunWorkInitResponse retVal = ((ServiceControl.MainServiceReference.MainServiceSoap)(this)).RunWorkInit(inValue);
            return retVal.Body.RunWorkInitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceControl.MainServiceReference.RunWorkInitResponse> ServiceControl.MainServiceReference.MainServiceSoap.RunWorkInitAsync(ServiceControl.MainServiceReference.RunWorkInitRequest request) {
            return base.Channel.RunWorkInitAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceControl.MainServiceReference.RunWorkInitResponse> RunWorkInitAsync() {
            ServiceControl.MainServiceReference.RunWorkInitRequest inValue = new ServiceControl.MainServiceReference.RunWorkInitRequest();
            inValue.Body = new ServiceControl.MainServiceReference.RunWorkInitRequestBody();
            return ((ServiceControl.MainServiceReference.MainServiceSoap)(this)).RunWorkInitAsync(inValue);
        }
    }
}
