//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18052
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceControl.NodeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cocoin.info/NodeService", ConfigurationName="NodeServiceReference.NodeServiceSoap")]
    public interface NodeServiceSoap {
        
        // CODEGEN: 命名空間 http://cocoin.info/NodeService 的項目名稱  RunResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://cocoin.info/NodeService/Run", ReplyAction="*")]
        ServiceControl.NodeServiceReference.RunResponse Run(ServiceControl.NodeServiceReference.RunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cocoin.info/NodeService/Run", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceControl.NodeServiceReference.RunResponse> RunAsync(ServiceControl.NodeServiceReference.RunRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Run", Namespace="http://cocoin.info/NodeService", Order=0)]
        public ServiceControl.NodeServiceReference.RunRequestBody Body;
        
        public RunRequest() {
        }
        
        public RunRequest(ServiceControl.NodeServiceReference.RunRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RunRequestBody {
        
        public RunRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunResponse", Namespace="http://cocoin.info/NodeService", Order=0)]
        public ServiceControl.NodeServiceReference.RunResponseBody Body;
        
        public RunResponse() {
        }
        
        public RunResponse(ServiceControl.NodeServiceReference.RunResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocoin.info/NodeService")]
    public partial class RunResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RunResult;
        
        public RunResponseBody() {
        }
        
        public RunResponseBody(string RunResult) {
            this.RunResult = RunResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NodeServiceSoapChannel : ServiceControl.NodeServiceReference.NodeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NodeServiceSoapClient : System.ServiceModel.ClientBase<ServiceControl.NodeServiceReference.NodeServiceSoap>, ServiceControl.NodeServiceReference.NodeServiceSoap {
        
        public NodeServiceSoapClient() {
        }
        
        public NodeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NodeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NodeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NodeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceControl.NodeServiceReference.RunResponse ServiceControl.NodeServiceReference.NodeServiceSoap.Run(ServiceControl.NodeServiceReference.RunRequest request) {
            return base.Channel.Run(request);
        }
        
        public string Run() {
            ServiceControl.NodeServiceReference.RunRequest inValue = new ServiceControl.NodeServiceReference.RunRequest();
            inValue.Body = new ServiceControl.NodeServiceReference.RunRequestBody();
            ServiceControl.NodeServiceReference.RunResponse retVal = ((ServiceControl.NodeServiceReference.NodeServiceSoap)(this)).Run(inValue);
            return retVal.Body.RunResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceControl.NodeServiceReference.RunResponse> ServiceControl.NodeServiceReference.NodeServiceSoap.RunAsync(ServiceControl.NodeServiceReference.RunRequest request) {
            return base.Channel.RunAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceControl.NodeServiceReference.RunResponse> RunAsync() {
            ServiceControl.NodeServiceReference.RunRequest inValue = new ServiceControl.NodeServiceReference.RunRequest();
            inValue.Body = new ServiceControl.NodeServiceReference.RunRequestBody();
            return ((ServiceControl.NodeServiceReference.NodeServiceSoap)(this)).RunAsync(inValue);
        }
    }
}
