//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySummary
    {
        public System.DateTime receiveDate { get; set; }
        public string stockId { get; set; }
        public Nullable<decimal> tradeRec { get; set; }
        public Nullable<decimal> tradeAmt { get; set; }
        public Nullable<decimal> tradeQty { get; set; }
        public Nullable<decimal> openPrice { get; set; }
        public Nullable<decimal> highPrice { get; set; }
        public Nullable<decimal> lowPrice { get; set; }
        public Nullable<decimal> lastPrice { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
