//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.DailyDetail = new HashSet<DailyDetail>();
            this.DailySummary = new HashSet<DailySummary>();
        }
    
        public string stockId { get; set; }
        public string name { get; set; }
        public string bzClass { get; set; }
        public string stockType { get; set; }
        public Nullable<System.DateTime> initTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    
        public virtual ICollection<DailyDetail> DailyDetail { get; set; }
        public virtual ICollection<DailySummary> DailySummary { get; set; }
    }
}
