//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18052
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeepService.KeepServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KeepServiceReference.KeepServiceSoap")]
    public interface KeepServiceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的項目名稱  receiveDate 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportCSV", ReplyAction="*")]
        KeepServiceReference.ExportCSVResponse ExportCSV(KeepServiceReference.ExportCSVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportCSV", ReplyAction="*")]
        System.Threading.Tasks.Task<KeepServiceReference.ExportCSVResponse> ExportCSVAsync(KeepServiceReference.ExportCSVRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的項目名稱  receiveDate 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DailyRateTask", ReplyAction="*")]
        KeepServiceReference.DailyRateTaskResponse DailyRateTask(KeepServiceReference.DailyRateTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DailyRateTask", ReplyAction="*")]
        System.Threading.Tasks.Task<KeepServiceReference.DailyRateTaskResponse> DailyRateTaskAsync(KeepServiceReference.DailyRateTaskRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的項目名稱  receiveDate 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WeeklyRateTask", ReplyAction="*")]
        KeepServiceReference.WeeklyRateTaskResponse WeeklyRateTask(KeepServiceReference.WeeklyRateTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WeeklyRateTask", ReplyAction="*")]
        System.Threading.Tasks.Task<KeepServiceReference.WeeklyRateTaskResponse> WeeklyRateTaskAsync(KeepServiceReference.WeeklyRateTaskRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportCSVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportCSV", Namespace="http://tempuri.org/", Order=0)]
        public KeepServiceReference.ExportCSVRequestBody Body;
        
        public ExportCSVRequest() {
        }
        
        public ExportCSVRequest(KeepServiceReference.ExportCSVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExportCSVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string receiveDate;
        
        public ExportCSVRequestBody() {
        }
        
        public ExportCSVRequestBody(string receiveDate) {
            this.receiveDate = receiveDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportCSVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportCSVResponse", Namespace="http://tempuri.org/", Order=0)]
        public KeepServiceReference.ExportCSVResponseBody Body;
        
        public ExportCSVResponse() {
        }
        
        public ExportCSVResponse(KeepServiceReference.ExportCSVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExportCSVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExportCSVResult;
        
        public ExportCSVResponseBody() {
        }
        
        public ExportCSVResponseBody(string ExportCSVResult) {
            this.ExportCSVResult = ExportCSVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DailyRateTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DailyRateTask", Namespace="http://tempuri.org/", Order=0)]
        public KeepServiceReference.DailyRateTaskRequestBody Body;
        
        public DailyRateTaskRequest() {
        }
        
        public DailyRateTaskRequest(KeepServiceReference.DailyRateTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DailyRateTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string receiveDate;
        
        public DailyRateTaskRequestBody() {
        }
        
        public DailyRateTaskRequestBody(string receiveDate) {
            this.receiveDate = receiveDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DailyRateTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DailyRateTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public KeepServiceReference.DailyRateTaskResponseBody Body;
        
        public DailyRateTaskResponse() {
        }
        
        public DailyRateTaskResponse(KeepServiceReference.DailyRateTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DailyRateTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DailyRateTaskResult;
        
        public DailyRateTaskResponseBody() {
        }
        
        public DailyRateTaskResponseBody(string DailyRateTaskResult) {
            this.DailyRateTaskResult = DailyRateTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WeeklyRateTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WeeklyRateTask", Namespace="http://tempuri.org/", Order=0)]
        public KeepServiceReference.WeeklyRateTaskRequestBody Body;
        
        public WeeklyRateTaskRequest() {
        }
        
        public WeeklyRateTaskRequest(KeepServiceReference.WeeklyRateTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WeeklyRateTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string receiveDate;
        
        public WeeklyRateTaskRequestBody() {
        }
        
        public WeeklyRateTaskRequestBody(string receiveDate) {
            this.receiveDate = receiveDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WeeklyRateTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WeeklyRateTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public KeepServiceReference.WeeklyRateTaskResponseBody Body;
        
        public WeeklyRateTaskResponse() {
        }
        
        public WeeklyRateTaskResponse(KeepServiceReference.WeeklyRateTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WeeklyRateTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WeeklyRateTaskResult;
        
        public WeeklyRateTaskResponseBody() {
        }
        
        public WeeklyRateTaskResponseBody(string WeeklyRateTaskResult) {
            this.WeeklyRateTaskResult = WeeklyRateTaskResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KeepServiceSoapChannel : KeepServiceReference.KeepServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KeepServiceSoapClient : System.ServiceModel.ClientBase<KeepServiceReference.KeepServiceSoap>, KeepServiceReference.KeepServiceSoap {
        
        public KeepServiceSoapClient() {
        }
        
        public KeepServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KeepServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeepServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeepServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KeepServiceReference.ExportCSVResponse KeepServiceReference.KeepServiceSoap.ExportCSV(KeepServiceReference.ExportCSVRequest request) {
            return base.Channel.ExportCSV(request);
        }
        
        public string ExportCSV(string receiveDate) {
            KeepServiceReference.ExportCSVRequest inValue = new KeepServiceReference.ExportCSVRequest();
            inValue.Body = new KeepServiceReference.ExportCSVRequestBody();
            inValue.Body.receiveDate = receiveDate;
            KeepServiceReference.ExportCSVResponse retVal = ((KeepServiceReference.KeepServiceSoap)(this)).ExportCSV(inValue);
            return retVal.Body.ExportCSVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KeepServiceReference.ExportCSVResponse> KeepServiceReference.KeepServiceSoap.ExportCSVAsync(KeepServiceReference.ExportCSVRequest request) {
            return base.Channel.ExportCSVAsync(request);
        }
        
        public System.Threading.Tasks.Task<KeepServiceReference.ExportCSVResponse> ExportCSVAsync(string receiveDate) {
            KeepServiceReference.ExportCSVRequest inValue = new KeepServiceReference.ExportCSVRequest();
            inValue.Body = new KeepServiceReference.ExportCSVRequestBody();
            inValue.Body.receiveDate = receiveDate;
            return ((KeepServiceReference.KeepServiceSoap)(this)).ExportCSVAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KeepServiceReference.DailyRateTaskResponse KeepServiceReference.KeepServiceSoap.DailyRateTask(KeepServiceReference.DailyRateTaskRequest request) {
            return base.Channel.DailyRateTask(request);
        }
        
        public string DailyRateTask(string receiveDate) {
            KeepServiceReference.DailyRateTaskRequest inValue = new KeepServiceReference.DailyRateTaskRequest();
            inValue.Body = new KeepServiceReference.DailyRateTaskRequestBody();
            inValue.Body.receiveDate = receiveDate;
            KeepServiceReference.DailyRateTaskResponse retVal = ((KeepServiceReference.KeepServiceSoap)(this)).DailyRateTask(inValue);
            return retVal.Body.DailyRateTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KeepServiceReference.DailyRateTaskResponse> KeepServiceReference.KeepServiceSoap.DailyRateTaskAsync(KeepServiceReference.DailyRateTaskRequest request) {
            return base.Channel.DailyRateTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<KeepServiceReference.DailyRateTaskResponse> DailyRateTaskAsync(string receiveDate) {
            KeepServiceReference.DailyRateTaskRequest inValue = new KeepServiceReference.DailyRateTaskRequest();
            inValue.Body = new KeepServiceReference.DailyRateTaskRequestBody();
            inValue.Body.receiveDate = receiveDate;
            return ((KeepServiceReference.KeepServiceSoap)(this)).DailyRateTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KeepServiceReference.WeeklyRateTaskResponse KeepServiceReference.KeepServiceSoap.WeeklyRateTask(KeepServiceReference.WeeklyRateTaskRequest request) {
            return base.Channel.WeeklyRateTask(request);
        }
        
        public string WeeklyRateTask(string receiveDate) {
            KeepServiceReference.WeeklyRateTaskRequest inValue = new KeepServiceReference.WeeklyRateTaskRequest();
            inValue.Body = new KeepServiceReference.WeeklyRateTaskRequestBody();
            inValue.Body.receiveDate = receiveDate;
            KeepServiceReference.WeeklyRateTaskResponse retVal = ((KeepServiceReference.KeepServiceSoap)(this)).WeeklyRateTask(inValue);
            return retVal.Body.WeeklyRateTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KeepServiceReference.WeeklyRateTaskResponse> KeepServiceReference.KeepServiceSoap.WeeklyRateTaskAsync(KeepServiceReference.WeeklyRateTaskRequest request) {
            return base.Channel.WeeklyRateTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<KeepServiceReference.WeeklyRateTaskResponse> WeeklyRateTaskAsync(string receiveDate) {
            KeepServiceReference.WeeklyRateTaskRequest inValue = new KeepServiceReference.WeeklyRateTaskRequest();
            inValue.Body = new KeepServiceReference.WeeklyRateTaskRequestBody();
            inValue.Body.receiveDate = receiveDate;
            return ((KeepServiceReference.KeepServiceSoap)(this)).WeeklyRateTaskAsync(inValue);
        }
    }
}
