//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18052
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkItem", Namespace="http://cocoin.info/MainService")]
    [System.SerializableAttribute()]
    public partial class WorkItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime receiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stockIdField;
        
        private int currentField;
        
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime receiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                if ((this.receiveDateField.Equals(value) != true)) {
                    this.receiveDateField = value;
                    this.RaisePropertyChanged("receiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string stockId {
            get {
                return this.stockIdField;
            }
            set {
                if ((object.ReferenceEquals(this.stockIdField, value) != true)) {
                    this.stockIdField = value;
                    this.RaisePropertyChanged("stockId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int current {
            get {
                return this.currentField;
            }
            set {
                if ((this.currentField.Equals(value) != true)) {
                    this.currentField = value;
                    this.RaisePropertyChanged("current");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cocoin.info/MainService", ConfigurationName="MainServiceReference.MainServiceSoap")]
    public interface MainServiceSoap {
        
        // CODEGEN: 命名空間 http://cocoin.info/MainService 的項目名稱  GetWorkResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://cocoin.info/MainService/GetWork", ReplyAction="*")]
        MainServiceReference.GetWorkResponse GetWork(MainServiceReference.GetWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cocoin.info/MainService/GetWork", ReplyAction="*")]
        System.Threading.Tasks.Task<MainServiceReference.GetWorkResponse> GetWorkAsync(MainServiceReference.GetWorkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWorkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWork", Namespace="http://cocoin.info/MainService", Order=0)]
        public MainServiceReference.GetWorkRequestBody Body;
        
        public GetWorkRequest() {
        }
        
        public GetWorkRequest(MainServiceReference.GetWorkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWorkRequestBody {
        
        public GetWorkRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWorkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWorkResponse", Namespace="http://cocoin.info/MainService", Order=0)]
        public MainServiceReference.GetWorkResponseBody Body;
        
        public GetWorkResponse() {
        }
        
        public GetWorkResponse(MainServiceReference.GetWorkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocoin.info/MainService")]
    public partial class GetWorkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MainServiceReference.WorkItem GetWorkResult;
        
        public GetWorkResponseBody() {
        }
        
        public GetWorkResponseBody(MainServiceReference.WorkItem GetWorkResult) {
            this.GetWorkResult = GetWorkResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MainServiceSoapChannel : MainServiceReference.MainServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainServiceSoapClient : System.ServiceModel.ClientBase<MainServiceReference.MainServiceSoap>, MainServiceReference.MainServiceSoap {
        
        public MainServiceSoapClient() {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MainServiceReference.GetWorkResponse MainServiceReference.MainServiceSoap.GetWork(MainServiceReference.GetWorkRequest request) {
            return base.Channel.GetWork(request);
        }
        
        public MainServiceReference.WorkItem GetWork() {
            MainServiceReference.GetWorkRequest inValue = new MainServiceReference.GetWorkRequest();
            inValue.Body = new MainServiceReference.GetWorkRequestBody();
            MainServiceReference.GetWorkResponse retVal = ((MainServiceReference.MainServiceSoap)(this)).GetWork(inValue);
            return retVal.Body.GetWorkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MainServiceReference.GetWorkResponse> MainServiceReference.MainServiceSoap.GetWorkAsync(MainServiceReference.GetWorkRequest request) {
            return base.Channel.GetWorkAsync(request);
        }
        
        public System.Threading.Tasks.Task<MainServiceReference.GetWorkResponse> GetWorkAsync() {
            MainServiceReference.GetWorkRequest inValue = new MainServiceReference.GetWorkRequest();
            inValue.Body = new MainServiceReference.GetWorkRequestBody();
            return ((MainServiceReference.MainServiceSoap)(this)).GetWorkAsync(inValue);
        }
    }
}
